import { gql } from '@apollo/client';
import client from '../apollo-client';

import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Launches {
        launches {
          mission_name
          mission_id
          rocket {
            rocket_name
            rocket {
              company
              name
              mass {
                kg
              }
            }
          }
          launch_site {
            site_name
          }
          launch_date_local
        }
      }
    `,
  });

  return {
    props: {
      launches: data.launches.slice(0, 4),
    },
  };
}

export default function Home({ launches }) {
  return (
    <div className='container mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
}
