import { gql } from '@apollo/client';
import client from '../apollo-client';

import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const bgImg = {
  backgroundImage: `url('https://images.pexels.com/photos/5632402/pexels-photo-5632402.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2')`,
  backgroundPosition: 'center',
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  height: '95vh',
};

export default function Home() {
  return (
    <div className='container mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-9/12 mx-auto' style={bgImg}>
        <div className='text-6xl text-center text-gray-900 mx-auto pt-20'>
          Welcome to our shop
        </div>
        <div className='text-4xl text-center text-gray-900 mx-auto my-6'>
          Start your experience now!
        </div>
      </div>
    </div>
  );
}
