import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const products = [
  { name: 'Product 1', price: 10, description: 'desc 1' },
  { name: 'Product 2', price: 20, description: 'desc 2' },
];
export default function Home() {
  return (
    <div className='container mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12 px-10 bg-grey-300'>
        <div>Text</div>
        {products.map((product, index) => (
          <>
            <div>{product.name}</div>
            <div>{product.description}</div>
          </>
        ))}
      </div>
    </div>
  );
}
